### ISSUE TITLE
con.sublime-snippet cannot be created in Windows

### ISSUE THREAD

**Issue by kunalbedi** [gerardroche/sublime-php-snippets#5]
Hi,

the sublime snippet named "con.sublime-snippet" cannot be created in Windows.
CON is a reserved keyword in windows.
Anything to do about it?

**Comment by gerardroche** [comment]
I'm afraid I don't understand. It works for me. What do you mean by reserved? Can you show me steps to reproduice it?

**Comment by kunalbedi** [comment]
Hi Gerard,

See this short video though it shows a file being renamed to "con.sublime-snippet".
https://www.screencast.com/t/SyVAdEuLL

Problem: the plugin installs well in to Sublime Text but the construct snippet named "con.sublime-snippet" does not work. Digging further I see that the file is in the package but is not created on my file system and hence inaccessible. 

The issue is with windows giving DOS based drivers name as keywords. A brief explanation is here: http://www.thewindowsclub.com/create-restricted-files-folders-con-aux-nul-click-windows

I was wondering if this filename can be renamed or something in your package so that it is still available for windows user. You mentioned that it works for you. Maybe you can tell me how you made it work.

thank you for your time in looking in to this matter.
Regards
Kunal Bedi

**Comment by gerardroche** [comment]
Hi kunalbedi.

screencast.com requires flash so I can't view the video. I also don't click on links I'm not familiar with. Copy and paste relevant information in the issue, people generally won't follow links to 3rd parties.

You need to explain the issue for me because I still don't understand. A file named "con.sublime-snippet" is not a reserved file name on Windows.

Here's what you can to do to test it:

Create a file named "con.sublime-snippet" in your Sublime Text User directory `Menu > Preferences > Browse Packages...`.

The file will be `Packages/User/con.sublime-snippet`.

With the snippet:

```
<snippet>
    <content><![CDATA[
${1:public} function __construct(${2:\$${3:param}${4: = ${5:null}}})${TM_PHP_SNIPPET_OPENING_BRACE:
\{}
	${3/.+/$this->$0 = \$$0;/}$0
}
]]></content>
    <tabTrigger>con</tabTrigger>
    <scopeAliases>language_construct</scopeAliases>
    <scope>source.php - comment - constant.other.class - entity.name - meta.catch - meta.class - meta.function.arguments - meta.use - string - variable.other - variable.parameter, source.php meta.class.php meta.block.php - comment - constant.other.class - entity.name - meta.catch - meta.function.arguments - meta.function.parameters - meta.use - string - variable.other - variable.parameter - meta.function.return-type</scope>
    <description>PHP: class constructor definition</description>
</snippet>
```

If Windows doesn't allow you to create that file it's not an issue with this package but with your system. You can test too by instead creating the file named something else e.g. `something_else.sublime-snippet`.

**Comment by gerardroche** [comment]
You are indeed correct, "con" is a reserved name on Windows:

> Do not use the following reserved names for the name of a file:
>
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended
>
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx
